require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DiamondsController do

  # This should return the minimal set of attributes required to create a valid
  # Diamond. As you add validations to Diamond, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DiamondsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all diamonds as @diamonds" do
      diamond = Diamond.create! valid_attributes
      get :index, {}, valid_session
      assigns(:diamonds).should eq([diamond])
    end
  end

  describe "GET show" do
    it "assigns the requested diamond as @diamond" do
      diamond = Diamond.create! valid_attributes
      get :show, {:id => diamond.to_param}, valid_session
      assigns(:diamond).should eq(diamond)
    end
  end

  describe "GET new" do
    it "assigns a new diamond as @diamond" do
      get :new, {}, valid_session
      assigns(:diamond).should be_a_new(Diamond)
    end
  end

  describe "GET edit" do
    it "assigns the requested diamond as @diamond" do
      diamond = Diamond.create! valid_attributes
      get :edit, {:id => diamond.to_param}, valid_session
      assigns(:diamond).should eq(diamond)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Diamond" do
        expect {
          post :create, {:diamond => valid_attributes}, valid_session
        }.to change(Diamond, :count).by(1)
      end

      it "assigns a newly created diamond as @diamond" do
        post :create, {:diamond => valid_attributes}, valid_session
        assigns(:diamond).should be_a(Diamond)
        assigns(:diamond).should be_persisted
      end

      it "redirects to the created diamond" do
        post :create, {:diamond => valid_attributes}, valid_session
        response.should redirect_to(Diamond.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved diamond as @diamond" do
        # Trigger the behavior that occurs when invalid params are submitted
        Diamond.any_instance.stub(:save).and_return(false)
        post :create, {:diamond => {}}, valid_session
        assigns(:diamond).should be_a_new(Diamond)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Diamond.any_instance.stub(:save).and_return(false)
        post :create, {:diamond => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested diamond" do
        diamond = Diamond.create! valid_attributes
        # Assuming there are no other diamonds in the database, this
        # specifies that the Diamond created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Diamond.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => diamond.to_param, :diamond => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested diamond as @diamond" do
        diamond = Diamond.create! valid_attributes
        put :update, {:id => diamond.to_param, :diamond => valid_attributes}, valid_session
        assigns(:diamond).should eq(diamond)
      end

      it "redirects to the diamond" do
        diamond = Diamond.create! valid_attributes
        put :update, {:id => diamond.to_param, :diamond => valid_attributes}, valid_session
        response.should redirect_to(diamond)
      end
    end

    describe "with invalid params" do
      it "assigns the diamond as @diamond" do
        diamond = Diamond.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Diamond.any_instance.stub(:save).and_return(false)
        put :update, {:id => diamond.to_param, :diamond => {}}, valid_session
        assigns(:diamond).should eq(diamond)
      end

      it "re-renders the 'edit' template" do
        diamond = Diamond.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Diamond.any_instance.stub(:save).and_return(false)
        put :update, {:id => diamond.to_param, :diamond => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested diamond" do
      diamond = Diamond.create! valid_attributes
      expect {
        delete :destroy, {:id => diamond.to_param}, valid_session
      }.to change(Diamond, :count).by(-1)
    end

    it "redirects to the diamonds list" do
      diamond = Diamond.create! valid_attributes
      delete :destroy, {:id => diamond.to_param}, valid_session
      response.should redirect_to(diamonds_url)
    end
  end

end
