require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PriceSnapshotsController do

  # This should return the minimal set of attributes required to create a valid
  # PriceSnapshot. As you add validations to PriceSnapshot, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PriceSnapshotsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all price_snapshots as @price_snapshots" do
      price_snapshot = PriceSnapshot.create! valid_attributes
      get :index, {}, valid_session
      assigns(:price_snapshots).should eq([price_snapshot])
    end
  end

  describe "GET show" do
    it "assigns the requested price_snapshot as @price_snapshot" do
      price_snapshot = PriceSnapshot.create! valid_attributes
      get :show, {:id => price_snapshot.to_param}, valid_session
      assigns(:price_snapshot).should eq(price_snapshot)
    end
  end

  describe "GET new" do
    it "assigns a new price_snapshot as @price_snapshot" do
      get :new, {}, valid_session
      assigns(:price_snapshot).should be_a_new(PriceSnapshot)
    end
  end

  describe "GET edit" do
    it "assigns the requested price_snapshot as @price_snapshot" do
      price_snapshot = PriceSnapshot.create! valid_attributes
      get :edit, {:id => price_snapshot.to_param}, valid_session
      assigns(:price_snapshot).should eq(price_snapshot)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PriceSnapshot" do
        expect {
          post :create, {:price_snapshot => valid_attributes}, valid_session
        }.to change(PriceSnapshot, :count).by(1)
      end

      it "assigns a newly created price_snapshot as @price_snapshot" do
        post :create, {:price_snapshot => valid_attributes}, valid_session
        assigns(:price_snapshot).should be_a(PriceSnapshot)
        assigns(:price_snapshot).should be_persisted
      end

      it "redirects to the created price_snapshot" do
        post :create, {:price_snapshot => valid_attributes}, valid_session
        response.should redirect_to(PriceSnapshot.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved price_snapshot as @price_snapshot" do
        # Trigger the behavior that occurs when invalid params are submitted
        PriceSnapshot.any_instance.stub(:save).and_return(false)
        post :create, {:price_snapshot => {}}, valid_session
        assigns(:price_snapshot).should be_a_new(PriceSnapshot)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PriceSnapshot.any_instance.stub(:save).and_return(false)
        post :create, {:price_snapshot => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested price_snapshot" do
        price_snapshot = PriceSnapshot.create! valid_attributes
        # Assuming there are no other price_snapshots in the database, this
        # specifies that the PriceSnapshot created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PriceSnapshot.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => price_snapshot.to_param, :price_snapshot => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested price_snapshot as @price_snapshot" do
        price_snapshot = PriceSnapshot.create! valid_attributes
        put :update, {:id => price_snapshot.to_param, :price_snapshot => valid_attributes}, valid_session
        assigns(:price_snapshot).should eq(price_snapshot)
      end

      it "redirects to the price_snapshot" do
        price_snapshot = PriceSnapshot.create! valid_attributes
        put :update, {:id => price_snapshot.to_param, :price_snapshot => valid_attributes}, valid_session
        response.should redirect_to(price_snapshot)
      end
    end

    describe "with invalid params" do
      it "assigns the price_snapshot as @price_snapshot" do
        price_snapshot = PriceSnapshot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PriceSnapshot.any_instance.stub(:save).and_return(false)
        put :update, {:id => price_snapshot.to_param, :price_snapshot => {}}, valid_session
        assigns(:price_snapshot).should eq(price_snapshot)
      end

      it "re-renders the 'edit' template" do
        price_snapshot = PriceSnapshot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PriceSnapshot.any_instance.stub(:save).and_return(false)
        put :update, {:id => price_snapshot.to_param, :price_snapshot => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested price_snapshot" do
      price_snapshot = PriceSnapshot.create! valid_attributes
      expect {
        delete :destroy, {:id => price_snapshot.to_param}, valid_session
      }.to change(PriceSnapshot, :count).by(-1)
    end

    it "redirects to the price_snapshots list" do
      price_snapshot = PriceSnapshot.create! valid_attributes
      delete :destroy, {:id => price_snapshot.to_param}, valid_session
      response.should redirect_to(price_snapshots_url)
    end
  end

end
